### ISSUE TITLE
Yafu project

### ISSUE THREAD

**Issue by sircristian1212** [NyanCatTW1/TouhouSongDatabase#1]
Hello,
I am in desperate need for help with a yafu project. I'm willing to pay whatever it takes.
Please let me know if you would have the time and interest to start a conversation.  Or if you don't have the possibility, please direct me to someone who does. Hope your account is still active and I am trully sorry for opening an issue on your project with this request. 

Thank you,
Chris

**Comment by NyanCatTW1** [comment]
It depends on how long the project will take us, how interesting we think it is, and the payment. We would like to know the details, and we also know a person who might be willing to give it a try. Find us on Discord, our nickname is the same as here, but in lowercase

**Comment by sircristian1212** [comment]
Friend request sent from sircristian
